### ISSUE TITLE
Please update Cake.Bower's reference of Cake.Core.

### ISSUE THREAD

**Issue by VictorioBerra** [wozzo/Cake.Bower#4]
```
Error: The assembly 'Cake.Bower, Version=0.4.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.22.0).
This assembly need to reference at least Cake.Core version 0.26.0.
Another option is to downgrade Cake to an earlier version.
It's not recommended, but you can explicitly opt-out of assembly verification
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true",
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
```

**Comment by gep13** [comment]
@VictorioBerra I am sure that the maintainer of this addin will get this updated as soon as possible.

In the meantime, if you don't "need" the latest features in Cake 0.26.0, the recommendation would be to pin to an earlier version of Cake:

https://cakebuild.net/docs/tutorials/pinning-cake-version

Or, to pass in the argument that is recommended in the above error message.

**Comment by wozzo** [comment]
Or you'd be welcome to PR. I'm thinking it should "just" be a case of changing the version in the projects and recompiling, [for example](https://github.com/cake-contrib/Cake.XdtTransform/pull/17/commits/fd51aab6138fb50096b49e9b6794772b4c1c1ed8).
If not I should be getting to this at the weekend

**Comment by VictorioBerra** [comment]
@wozzo is there a way to specify the location of bower to execute?

**Comment by wozzo** [comment]
@VictorioBerra The BowerSettings class inherits from ToolSettings which has a ToolPath property you can set. That should do it, but I don't think I've tested it with that.

**Comment by wozzo** [comment]
New version released.
